### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by iuzer** [GavickPro/GK-JomSocial-Feed#2]
when a user make a new photo album, the grid loads not the last image added in album but linking to the last image added thumb. why ?

**Comment by dziudek** [comment]
Solution was posted here: 
https://github.com/GavickPro/Grid-GK5/issues/11 ;)

**Comment by iuzer** [comment]
thank you very much for your kind support ! ...  ( sorry for publishing in the wrong place the issue ) best regards !
