### ISSUE TITLE
Selected status doesn't exist

### ISSUE THREAD

**Issue by pfrankowski** [GavickPro/GK-JomSocial-Feed#4]
Statuses are added. Latest version of JomSocial, Module, and Joomla 3.3.x
https://www.gavick.com/forums/m-social/gk-jomsocial-feed-selected-status-doesn-t-exist-39650.html

what is funny when I removed 
AND a.access = 0

all works okey.

**Comment by dziudek** [comment]
This fix should solve this issue: https://github.com/GavickPro/GK-JomSocial-Feed/commit/7af270cae659e40938f68f8d794342e39e00c6c9

It seems that the global access value has been changed from 0 to 10.
